### ISSUE TITLE
What directory?

### ISSUE THREAD

**Issue by roadtripguy** [zayamatias/flightgear#1]
Sorry for the dumb question but I cannot figure out what directories to put these files.  I am on windows and I do not see an ETC folder in either the ~appdata\roaming\flightgear.org or ~\program files\FlightGear 2020.3\data or ~\program files\FlightGear 2020.3\bin

**Comment by zayamatias** [comment]
Hi, the /etc/ directory refers to Linux. There's possibly something similar in Windows but unfortunately FlightGear HID event subsystem (which I use to communicate between the instruments and FG itself) is not properly working under Windows. You can still try placing all files in the other directories and see if it works. If you get to the point where you copy the files to a Pico and then connect it to the Windows machine, you should see it under Human Interface Devices in the 'devices' section of the control panel. Hope this helps, and apologies if it was not clear enough that these instruments will not work under windows until FG gets fixed on that field.

**Comment by zayamatias** [comment]
We will have to wait until his event subsystem is working under windows.
